# Use the official PostgreSQL image as the base
FROM postgres:16

# Set environment variables
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=arif
ENV POSTGRES_DB=travels

# (Optional) Copy init script(s) into container to run at first startup
# COPY db/migration/ /docker-entrypoint-initdb.d/